
#! /usr/bin/env python
import argparse
from os import getcwd
import vcf as pyvcf
import yaml

def retrieve_match_snp_genotype(vcf_file, genotypes):
    vcf_reader = pyvcf.Reader(filename=vcf_file)
    genotype_match_per_snp = {}
    for genotype in genotypes:
        for snp in genotype.get("snp"):
            records_match = []
            records = vcf_reader.fetch(snp.get("chrom"), snp.get("start"), snp.get("end"))
            for record in records:
                if record.samples[0].gt_bases == snp.get("variant_genotype"):
                    records_match.append(True)
                else:
                    records_match.append(False)
            if any(records_match):
                genotype_match_per_snp.setdefault(genotype.get("genotype_id"), []).append(True)
            elif records_match:
                genotype_match_per_snp.setdefault(genotype.get("genotype_id"), []).append(False)
            elif next(records, None) is None:
                print("Remove genotype, fetch has no records for variant {}".format(snp.get("variant_id")))
                genotype_match_per_snp.setdefault(genotype.get("genotype_id"), []).append(False)
            else:
                print("Something went wrong?")
    return(genotype_match_per_snp)


def retrieve_match_phenotype_and_write(genotype_match_per_snp, translation_table, output_path, output_prefix, sample):
    with open("{path}/{prefix}.txt".format(path=output_path, prefix=output_prefix), 'w') as outfile:
        print("sample\tgenotype_match")
        for genotype_id, genotype_match in genotype_match_per_snp.items():
            if all(genotype_match):
                print("{sample}\t{gt}".format(
                    sample=sample, 
                    gt=translation_table[genotype_id].get("genotype_autogenerated_name")
                    ))


def main(translation_file, vcf_file, output_path, output_prefix, sample):
    with open(translation_file) as translation_file:
        translation_table = yaml.load(translation_file, Loader=yaml.FullLoader)
    genotype_match_per_snp = retrieve_match_snp_genotype(vcf_file=vcf_file, genotypes=translation_table.values())
    retrieve_match_phenotype_and_write(
        genotype_match_per_snp=genotype_match_per_snp, 
        translation_table=translation_table, 
        output_path=output_path, 
        output_prefix=output_prefix, 
        sample=sample)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="Translate variant genotype to a pharmacogentics phenotype.",
                                     formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument("-t", "--table", type=str, required=True, help="File path and name of translation table (.yaml).")
    parser.add_argument("-i", "--input", type=str, required=True, help="File path and name of compressed VCF (.vcf.gz).")
    parser.add_argument("-s", "--sample", type=str, required=True, help="Sample identifier.")
    parser.add_argument("-o", "--output_path", type=str, required=False, default=getcwd(), help="File path to store output.")
    parser.add_argument("-p", "--output_prefix", type=str, required=False, 
                        help="Output prefix to use as output filename. (default: the provided sample identifier)")
    args = parser.parse_args()
    if not args.output_prefix:
        args.output_prefix = args.sample
	main(
        translation_file=args.table, 
        vcf_file=args.input, 
        output_path=args.output_path, 
        output_prefix=args.output_prefix, 
        sample=args.sample)
