import pandas as pd
from pypgx.sdk import utils as sdk
from os import path


def import_clean_excel(file_path: str) -> pd.DataFrame:
    """ Import the excel genotype/fenotype
    translation table into pandas. This function takes into account the spacer rows '---' and
    missing values.

        Arguments:
                file_path -- file path to the excel file
        Returns:
                pd.DataFrame -- in a cleaned format
    """
    data = pd.read_excel(file_path, engine='openpyxl')

    # Drop the spacer lines
    data = data[~data['genotype_id'].astype(str).str.contains('---')]
    data['variant_id'] = data['variant_id'].apply(lambda val: val.split("_")[1].replace("\t",""))


    # Fill missing values in the 'gene' column with the previous filled value data['gene'] =
    data['gene'] = data['gene'].ffill()
    data['genotype_realname'] = data['genotype_realname'].ffill()
    data['genotype_autogenerated_name'] =  data[
        'genotype_autogenerated_name'].ffill()
    data["gstandard phenotype name \n(thnm50)"] = data["gstandard phenotype name \n(thnm50)"].ffill()

    return data

def get_vcf_identifier(vcf_line: list) -> tuple:
    return (vcf_line[0], vcf_line[1])


def import_dbsnp(file_path: str) -> dict:
    """ Creates a lookup table to match genomic positions (chrom, position) with rs_ids
    """
    rs_db = {}
    with open(file_path) as dbsnp_vcf:
        for line in dbsnp_vcf:
            if line.startswith("#"):
                continue

            line = line.strip().split()
            # creating an key out of CHR, POS
            identifier = get_vcf_identifier(line)

            if identifier in rs_db:
                rs_db[identifier].append(line[2])
            else:
                rs_db[identifier] = [line[2]]

    return rs_db

def has_cnv_calls(pypgx_directory):
    return path.exists(f"{pypgx_directory}/cnv-calls.zip") # File name is always the same

def import_cnv_calls(pypgx_directory):
    cnv_calls_df = sdk.Archive.from_file(f"{pypgx_directory}/cnv-calls.zip").data
    cnv_call = cnv_calls_df["CNV"].iloc[0]
    return cnv_call
