#!/usr/bin/env python3

import unittest
import pandas as pd
from itertools import chain

import call_star_alleles_excel
import sample
import databases


class TestStarCalling(unittest.TestCase):

    def setUp(self):
        self.CYP2B6rs_db = {
            ("19", "41009358"): ["rs2279343"],
            ("19", "41012316"): ["rs28399499"],
            ("19", "41006936"): ["rs3745274"]
        }

        self.CYP2C9rs_db = {
            ("10", "94981296"): ["rs1057910"],
            ("10", "94942290"): ["rs1799853"],
            ("10", "94981224"): ["rs28371685"],
            ("10", "94981301"): ["rs28371686"]
        }

        self.merged_rs_db = {**self.CYP2B6rs_db, **self.CYP2C9rs_db}

        self.GT_columns = ["genotype_id", "gene", "genotype_realname", "genotype_autogenerated_name",
                           "variant_id", "variant_result", "g-standaard \ntsitnr",
                           "gstandard phenotype name \n(thnm50)", "genotype_show"]

        self.CYP2B6_GTs = [
            ["10","CYP2B6", "wildtype/wildtype", "CYP2B6:wildtype/wildtype", "rs2279343", "A:A",
             "1342","EXTENSIVE/NORMAL METABOLIZER","*1/*1"],
            ["10","CYP2B6", "wildtype/wildtype", "CYP2B6:wildtype/wildtype", "rs28399499", "T:T",
             "1342","EXTENSIVE/NORMAL METABOLIZER","*1/*1"],
            ["10","CYP2B6", "wildtype/wildtype", "CYP2B6:wildtype/wildtype", "rs3745274", "G:G",
             "1342","EXTENSIVE/NORMAL METABOLIZER","*1/*1"],

            ["10","CYP2B6", "*18/*18", "CYP2B6:*18/*18", "rs2279343", "A:A", "1342",
             "POOR METABOLIZER","*18/*18"],
            ["10","CYP2B6", "*18/*18", "CYP2B6:*18/*18", "rs28399499", "C:C", "1342",
             "POOR METABOLIZER","*18/*18"],
            ["10","CYP2B6", "*18/*18", "CYP2B6:*18/*18", "rs3745274", "G:G", "1342",
             "POOR METABOLIZER", "*18/*18"]
        ]

        self.vcf_1_1 = [
            ["19", "41009358", ".", "A", "T", "30", "PASS", "GT:AD:DP", "0/0:30;30"],
            ["19", "41012316", ".", "A", "T", "30", "PASS", "GT:AD:DP", "1/1:30;30"],
            ["19", "41006936", ".", "G", "T", "30", "PASS", "GT:AD:DP", "0/0:30;30"]
        ]
        self.vcf_1_1_and_other = [
            ["19", "41009358", ".", "A", "T", "30", "PASS", "GT:AD:DP", "0/0:30;30"],
            ["19", "41012316", ".", "A", "T", "30", "PASS", "GT:AD:DP", "1/1:30;30"],
            ["19", "41006936", ".", "G", "T", "30", "PASS", "GT:AD:DP", "0/0:30;30"],
            ["10", "94981301", ".", "G", "T", "30", "PASS", "GT:AD:DP", "0/0:30;30"],
        ]

        self.vcf_1_1_ref_only = [
            ["19", "41009358", ".", "A", ".", "30", "PASS", "GT:AD:DP", "0/0:30;30"],
            ["19", "41012316", ".", "T", ".", "30", "PASS", "GT:AD:DP", "0/0:30;30"],
            ["19", "41006936", ".", "G", ".", "30", "PASS", "GT:AD:DP", "0/0:30;30"]
        ]

        self.vcf_18_18 = [
            ["19", "41009358", ".", "A", "T", "30", "PASS", "GT:AD:DP", "0/0:30;30"],
            ["19", "41012316", ".", "A", "C", "30", "PASS", "GT:AD:DP", "1/1:30;30"],
            ["19", "41006936", ".", "G", "T", "30", "PASS", "GT:AD:DP", "0/0:30;30"]
        ]

        self.vcf_18_18_and_non_rsID = [
            ["19", "41009358", ".", "A", "T", "30", "PASS", "GT:AD:DP", "0/0:30;30"],
            ["19", "41012316", ".", "A", "C", "30", "PASS", "GT:AD:DP", "1/1:30;30"],
            ["19", "41006936", ".", "G", "T", "30", "PASS", "GT:AD:DP", "0/0:30;30"],
            # random line without rsID
            ["1", "431420312", ".", "G", "G", "30", "PASS", "GT:AD:DP", "0/0:30:30"]
        ]

        self.vcf_1_1_18_18 = self.vcf_1_1 + self.vcf_18_18


        self.vcf_incomplete = [
            ["19", "41009358", ".", "A", "T", "30", "PASS", "GT:AD:DP", "0/0:30;30"],
            ["19", "41012316", ".", "A", "T", "30", "PASS", "GT:AD:DP", "1/1:30;30"]
        ]

        self.vcf_incomplete_call = [
            ["19", "41009358", ".", "A", "T", "30", "PASS", "GT:AD:DP", "0/0:30;30"],
            ["19", "41012316", ".", "A", "T", "30", "PASS", "GT:AD:DP", "1/1:30;30"],
            ["19", "41006936", ".", "G", "T", "30", "PASS", "GT:AD:DP", "./0:30;30"]
        ]

        self.rs_IDs1_1 = [sample.Sample.import_rsIDs(line, self.CYP2B6rs_db)
                            for line in self.vcf_1_1]

        self.rs_IDs1_1_and_other = [sample.Sample.import_rsIDs(line, self.merged_rs_db)
                                        for line in self.vcf_1_1_and_other]

        self.rs_IDs1_1_ref_only = [sample.Sample.import_rsIDs(line, self.CYP2B6rs_db)
                                   for line in self.vcf_1_1_ref_only]

        self.rs_IDs18_18 = [sample.Sample.import_rsIDs(line, self.CYP2B6rs_db)
                                for line in self.vcf_18_18]

        self.rs_IDs18_18_and_non_rsID = [sample.Sample.import_rsIDs(line, self.CYP2B6rs_db)
                                            for line in self.vcf_18_18_and_non_rsID]
        self.rs_IDs1_1_18_18 = [sample.Sample.import_rsIDs(line, self.merged_rs_db)
                                            for line in self.vcf_1_1_18_18]

        self.rs_IDs_incomplete = [sample.Sample.import_rsIDs(line, self.CYP2B6rs_db)
                                    for line in self.vcf_incomplete]

        self.rs_IDs_incomplete_call = [sample.Sample.import_rsIDs(line, self.CYP2B6rs_db)
                                       for line in self.vcf_incomplete_call]

        self.pgx_gene = "CYP2B6"
        self.data_subset_CYP2B6 = pd.DataFrame(self.CYP2B6_GTs, columns=self.GT_columns)

    def test_rs_DB_lookup(self):
        """ Double check that a locus returns the expected rs ID
        """
        self.assertEqual(self.CYP2B6rs_db[("19", "41009358")], ["rs2279343"])

    def test_vcf_import(self):
        """Implicitly tests sample.GT_to_Nucleotides() """

        self.assertCountEqual(self.rs_IDs1_1,
                              [["rs2279343;A:A"], ["rs28399499;T:T"], ["rs3745274;G:G"]])
        self.assertCountEqual(self.rs_IDs1_1_and_other,
                              [["rs2279343;A:A"], ["rs28399499;T:T"], ["rs3745274;G:G"],
                               ["rs28371686;G:G"]])
        self.assertCountEqual(self.rs_IDs18_18,
                              [["rs2279343;A:A"], ["rs28399499;C:C"], ["rs3745274;G:G"]])
        self.assertCountEqual(self.rs_IDs18_18_and_non_rsID,
                              [["rs2279343;A:A"], ["rs28399499;C:C"], ["rs3745274;G:G"], []])


    def test_hom_wildtype_CYP2B6(self):
        # Contains *1/*1 variants
        rs_IDs = list(chain(*self.rs_IDs1_1))
        self.assertEqual(
            call_star_alleles_excel.genotype("CYP2B6", self.data_subset_CYP2B6, rs_IDs),
            "CYP2B6:wildtype/wildtype"
        )
    def test_hom_18_18_CYP2B6(self):
        # Contains *18/*18 variants
        rs_IDs = list(chain(*self.rs_IDs18_18))
        self.assertEqual(
            call_star_alleles_excel.genotype("CYP2B6", self.data_subset_CYP2B6, rs_IDs),
            "CYP2B6:*18/*18"
        )
    def test_hom_wildtype_noise_CYP2B6(self):
        # Contains *1/*1 variants and one other unrelated variant with rs ID
        rs_IDs = list(chain(*self.rs_IDs1_1_and_other))
        self.assertEqual(
            call_star_alleles_excel.genotype("CYP2B6", self.data_subset_CYP2B6, rs_IDs),
            "CYP2B6:wildtype/wildtype"
        )

    def test_hom_wildtype_ref_callsCYP2B6(self):
        # Contains *1/*1 variantsn
        rs_IDs = list(chain(*self.rs_IDs1_1_ref_only))
        self.assertEqual(
            call_star_alleles_excel.genotype("CYP2B6", self.data_subset_CYP2B6, rs_IDs),
            "CYP2B6:wildtype/wildtype"
        )

    def test_hom_18_18_nonRS_CYP2B6(self):
        # Contains *18/*18 variants and one without an rs ID
        rs_IDs = list(chain(*self.rs_IDs18_18_and_non_rsID))
        self.assertEqual(
            call_star_alleles_excel.genotype("CYP2B6", self.data_subset_CYP2B6, rs_IDs),
            "CYP2B6:*18/*18"
        )

    def test_two_phenotypes_CYP2B6(self):
        # Contains both the *1/*1 and *18/*18 variants
        rs_IDs = list(chain(*self.rs_IDs1_1_18_18))
        self.assertEqual(
            call_star_alleles_excel.genotype("CYP2B6", self.data_subset_CYP2B6, rs_IDs),
            "CYP2B6:*18/*18"
        )
    def test_incomplete_genotype_set_CYP2B6(self):
        # Incomplete, so no genotype call
        rs_IDs = list(chain(*self.rs_IDs_incomplete))
        self.assertEqual(
            call_star_alleles_excel.genotype("CYP2B6", self.data_subset_CYP2B6, rs_IDs),
            "Inconclusive"
        )

    def test_incomplete_genotyping_call_CYP2B6(self):
        # Incomplete genotyping call (i.e. 0/1)
        rs_IDs = list(chain(*self.rs_IDs_incomplete_call))
        self.assertEqual(
            call_star_alleles_excel.genotype("CYP2B6", self.data_subset_CYP2B6, rs_IDs),
            "Inconclusive"
        )


    def test_genotype_to_phenotype(self):
        self.assertEqual(
            call_star_alleles_excel.get_phenotype(genotype="CYP2B6:wildtype/wildtype",
                                                  data=self.data_subset_CYP2B6),
            "EXTENSIVE/NORMAL METABOLIZER")
if __name__ == "__main__":
    unittest.main()

