name: nf-core linting
# This workflow is triggered on pushes and PRs to the repository.
# It runs `nextflow lint` and markdown lint tests to ensure that the code meets basic Nextflow linting guidelines.
on:
  push:
    branches:
      - main
      - develop
  pull_request:
  release:
    types: [published]

jobs:
  nf-core:
    runs-on: ubuntu-latest
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v4

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          architecture: "x64"

      - name: Run nextflow lint
        run: |
          nextflow lint -o extended . | tee lint_results.txt
          {
            echo '```'
            cat lint_results.txt
            echo '```'
          } > lint_results.md

      - name: Save PR number
        if: ${{ always() }}
        run: echo ${{ github.event.pull_request.number }} > PR_number.txt

      - name: Upload linting log file artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: linting-logs
          path: |
            lint_log.txt
            lint_results.md
            PR_number.txt
