name: nf-core linting
# This workflow is triggered on pushes and PRs to the repository.
# It runs `nextflow lint` and markdown lint tests to ensure that the code meets basic Nextflow linting guidelines.
on:
  push:
    branches:
      - main
      - develop
  pull_request:
  release:
    types: [published]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install nf-core==3.5.1
      - run: |
          nf-core pipelines lint \
          --key nextflow_config
    
